version: '3.9'

services:
  jenkins-android:
    build: ./jenkins-android
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - ./utility:/utility
    ports:
      - "80:80"
      - "443:443"
    environment:
      JENKINS_ADDRESS: "jenkins-android"
      DOMAIN_NAME: ${DOMAIN_NAME}
      KEYS_FOLDER: /etc/letsencrypt/live/${DOMAIN_NAME}
      WAIT_FOR_IT_TIME: ${WAIT_FOR_IT_TIME}
  certbot:
    build: ./certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    environment:
      NGINX_ADDRESS: "nginx"
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      KEYS_FOLDER: /etc/letsencrypt/live/${DOMAIN_NAME}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WAIT_FOR_IT_TIME: ${WAIT_FOR_IT_TIME}
    depends_on:
      - nginx


volumes:
  static:
  certbot-conf:
  certbot-www:
