version: '3.9'

services:
  backend:
    build: ./backend

    volumes:
      - static:/usr/src/app/static

    environment:
      BASE_URL: ${DOMAIN_NAME}
      ADMIN_ACCESS_TOKEN: ${ADMIN_ACCESS_TOKEN}
      IS_DEBUG_VERSION: ${IS_DEBUG_VERSION}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
  nginx:
    build: ./nginx
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - ./utility:/utility
    ports:
      - "80:80"
      - "443:443"
    environment:
      BACKEND_ADDRESS: "backend:80"
      DOMAIN_NAME: ${DOMAIN_NAME}
      KEYS_FOLDER: /etc/letsencrypt/live/${DOMAIN_NAME}
      WAIT_FOR_IT_TIME: ${WAIT_FOR_IT_TIME}
  certbot:
    build: ./certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - ./utility:/utility
    depends_on:
      - nginx
    environment:
      NGINX_ADDRESS: "nginx:80"
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      KEYS_FOLDER: /etc/letsencrypt/live/${DOMAIN_NAME}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WAIT_FOR_IT_TIME: ${WAIT_FOR_IT_TIME}
      IS_DEBUG_VERSION: ${IS_DEBUG_VERSION}



volumes:
  static:

  certbot-conf:
  certbot-www:

  jenkins-root:
  jenkins-log:
  jenkins-home:
